# 0703 Promise 规范

## PromiseA+规范

### 术语

1. promise 是一个有 then 方法的对象或函数，它遵循 promiseA+规范
2. thenable 是一个有 then 方法的对象或函数
3. value 是 promise 状态成功时的值，也就是 resolve 的参数，可以是任何类型
4. reason 是 promise 状态失败时的值，也是 reject 的参数，表示拒绝的原因
5. exception throw 抛出的异常

---

### 规范

### Promise States

1. pending
   1.1 初始状态
   1.2 在 resolve 或 reject 之前都处于 pending 状态
   1.3 resolve -> fulfilled
   1.4 reject -> rejected

2. fulfilled
   2.1 最终态，不可改变
   2.2 必须拥有一个 value 值. 可以为 undefined
3. rejected
   3.1 最终态，不可改变
   3.2 必须拥有一个 reason. 可以为 undefined

pending -> resolve(value) -> fulfilled

pending -> reject(value) -> rejected

### then

Promise 必须提供一个 then 方法，用来访问最终的结果，无论是 value 还是 reason

catch 后如果成功返回一个值，那么成功后返回的值也会被后面的 then 接收，举个 🌰

```js
new Promise((resolve, reject) => {
  reject("reject");
})
  .catch((reason) => {
    console.log("catch reason:", reason);
    return reason;
  })
  .then((res) => {
    console.log("then value:", res);
  });
```

打印结果：
catch reason: reject
then value: reject

1. 参数要求
   1.1 onFulfilled 必须是函数类型，如果不是函数，应该被忽略
   1.2 onRejected 必须是函数类型，如果不是函数，应该被忽略

2. onFulfilled 特性
   2.1 在 promise 变成 fulfilled 时， 应该调用 onFulfilled，参数是 value
   2.2 在 promise 变成 fulfilled 之前， 不应该调用 onFulfilled
   2.3 只能被调用一次.(_需要一个变量来限制执行次数_)

Pending -> resolve(value) -> fulfilled -> onFulfilled(value)
状态变化导致函数的触发，可以使用 getter 和 setter 来实现

3. onRejected 特性
   3.1 在 promise 变成 onRejected 时， 应该调用 onRejected，参数是 reason
   3.2 在 promise 变成 onRejected 之前， 不应该调用 onRejected
   3.3 只能被调用一次

4. onFulfilled 和 onRejected 应该是微任务
   queueMicrotask 实现微任务调用

5. Then 方法可以被调用多次
   5.1 promise 变成 fulfilled 之后，所有 onFulfilled 的回调都应该按照 then 的顺序执行

```js
promise.then(cb1).then(cb2).then(cb3);

let promise = new Promise();
promise.then(cb1);
promise.then(cb2);
promise.then(cb3);
```

5.2 promise 变成 rejected 之后，所有 onRejected 的回调都应该按照 then 的顺序执行

6. 返回值
   then 的返回值是一个 promise

```js
promise2 = promise1.then(onFulfilled, onRejected);
```

6.1 onFulfilled 或 onRejected 执行的函数结果为 x，调用 resolvePromise.
6.2 onFulfilled 或 onRejected 执行时抛出异常，promise2 需要被 reject.
6.3 如果 onFulfilled 不是一个函数，promise2 以 promise1 的 value 触发 fulfilled._值的透传_
6.4 如果 onRejected 不是一个函数，promise2 以 promise1 的 reason 触发 rejected.

7. resolvePromise

```js
resolvePromise(promise2, x, resolve, reject);
```

7.1 如果 promise2 和 x 相等， reject TypeError
promise2 和 x 相等会导致无限循环调用

7.2 如果 x 是一个 promise
如果 x 是 pending，promise 必须等待/pending 直到 x fulfilled / rejected
如果 x 是 fulfilled， fulfill promise with the same value.
如果 x 是 rejected， reject promise with the same reason.
7.3 如果不是一个 promise
如果是 object 或者 function，判断有没有 then 方法*（是不是 PromiseLike）*
x = x.then -> 如果报错 直接 reject promise with e as the reason.
如果 then 是函数: _promise2 的结构就是 then 的结果，这一步可能报错，因为这个 then 是不可信任的 then 方法，要添加 try/catch 并且确保函数只会被执行一次_
then.call(x, (y) => resolvePromise(promise2, y, resolve, reject),(e) => reject(e))
如果 then 方法执行报错
如果 resolvePromiseFn 或者 rejectPromise 已经被调用，则忽略
否则 reject promise with e as the reason
如果 then 不是函数，则直接 resolve(x)，即 fulfill promise with x.
